### ISSUE TITLE
How to turn off the esc key overlay?

### ISSUE THREAD

**Issue by piersolenski** [godbout/kindaVim.theapp#11]
<img width="176" alt="CleanShot 2021-12-08 at 02 11 16@2x" src="https://user-images.githubusercontent.com/1285419/145136069-93c4b594-9330-4ad1-9e98-d49f8934e4fb.png">

Is this coming from the app or macOS? Couldn't find a way to disable it via the preferences... According to the videos it should change on keypress but for me it just stays stuck on `esc`.

**Comment by godbout** [comment]
😬️
oops. this is from kindaVim. this is supposed to be only for me to record the YouTube videos. i've added the overlay recently for when you ENTER Normal Mode. nice fuck up obviously. beta 6 will be out early then, with a fix. probably later today. thanks for reporting!

**Comment by godbout** [comment]
beta 6 out. if you still have that overlay then i'll give up development forever.

**Comment by godbout** [comment]
thanks for the report btw. greatly appreciated!

**Comment by piersolenski** [comment]
no worries!
