### ISSUE TITLE
fails lamely with some Catalyst apps (at least iMessage, Podcasts)

### ISSUE THREAD

**Issue by godbout** [godbout/kindaVim.theapp#18]
bug with the AX API and/or Catalyst apps. reported as FB9813359. demo at: https://github.com/godbout/AXBugsWithCatalystApps/

**Comment by godbout** [comment]
workaround in 1b13.

**Comment by godbout** [comment]
@jandamm you can now use the Accessibility Strategy in Messages (Podcasts, blah blah). but you'll need to put those in the `PGR Mode`, else the text can't be deleted. enjoy 🎄️

**Comment by jandamm** [comment]
Happy 🎄 as well.
Feature works nicely :)

**Comment by godbout** [comment]
yeah, much better than the Keyboard Strategy where you're like "hmm no i shouldn't say that, let me delete" press `cc` -> message sent 😯️ LMAO
