### ISSUE TITLE
suggested movements

### ISSUE THREAD

**Issue by tthkbw** [godbout/kindaVim.theapp#20]
ctrl-f, ctrl-b, ctrl-u, ctrl-d for scrolling by pages and half pages.

But you probably don't know the size of the page, so perhaps a useful default for these, like 20 lines for a page and 10 for half page?

I have been using Karabiner for vim functionality in macOS text fields for years. This seems a good alternative. I have disabled Karabiner and will try kindaVim and see how it goes.

**Comment by godbout** [comment]
`CTRL-U` and `CTRL-D` are implemented: https://github.com/godbout/kindaVim.theapp#kv-keyboard-strategy (although only defined in the Keyboard Strategy but it works for both. will update the docs, thanks!)
they're not working for you? if not in which app?

`CTRL-F` and `CTRL-B` not done yet.

actually in theory kV can query the Visible Character Range of a field. in practice there's many times where the data sent back by the APIs is wrong. for example in browsers. so if you get out of the visibility in a text field, you'll see that you lose the cursor. not sure yet how to handle those API bugs so currently i'm cheating 😅️ the page scrolling is done through key remapping. i'll see if i can get something similar for those two moves missing. if yes i'll add them in the next beta.

**Comment by godbout** [comment]
KE is gonna be better for customization. but kV reads and manipulates text when i can, so it's not key remapping, it's text manipulation. not counting the bug you may find, it's Vim.

you can use both KE and kV together btw. KE adds a Virtual Keyboard on a low level, so for kV it just grabs what's coming. you could remap keys through KE *before* kV reads them.

**Comment by godbout** [comment]
> `CTRL-U` and `CTRL-D` are implemented: https://github.com/godbout/kindaVim.theapp#kv-keyboard-strategy (although only defined in the Keyboard Strategy but it works for both. will update the docs, thanks!) they're not working for you? if not in which app?
> 
> `CTRL-F` and `CTRL-B` not done yet.
> 
> actually in theory kV can query the Visible Character Range of a field. in practice there's many times where the data sent back by the APIs is wrong. for example in browsers. so if you get out of the visibility in a text field, you'll see that you lose the cursor. not sure yet how to handle those API bugs so currently i'm cheating 😅️ the page scrolling is done through key remapping. i'll see if i can get something similar for those two moves missing. if yes i'll add them in the next beta.

ah you mean with the caret also moving right? currently it scrolls but the caret stays at its current position. not like Vim yeah.

**Comment by godbout** [comment]
> will update the docs, thanks!) they're not working for you? if not in which app?

ultimately not gonna add because `CTRL-U` and `CTRL-D` are not working like in Vim.

**Comment by tthkbw** [comment]
My bad. CTRL-U and CTRL-D work to scroll. I almost never use them, I use CTRL-F and CTRL-B. 

And yes, in text fields, they would be much more useful if the caret moved when they were used, although I can see this could be confusing in some circumstances.

**Comment by godbout** [comment]
ok now i remember why i didn't add `CTRL-U` and `CTRL-D` to the Accessibility Strategy in the docs. it's just not done. currently it's just a fallback to the Keyboard Strategy. i'll add `CTRL-F` and `CTRL-B` for the next be'a but it's gonna work the same. proper Accessibility Strategy support will come next year (LOL).

**Comment by godbout** [comment]
added in 1b15 for Keyboard Strategy. Accessibility Strategy with caret positioning will have to wait 🙈️
