### ISSUE TITLE
caps lock as entry to normal mode

### ISSUE THREAD

**Issue by tthkbw** [godbout/kindaVim.theapp#21]
I am used to using CapsLock as the entry point to my vim functionality on macOS, primarily because I used Karabiner for years. 

I tried to map CapsLock as the shortcut for kindaVim, but it doesn't work. I currently use system mapping so CapsLock is escape and this at least maintains my muscle memory from years of Karabiner. 

However, it is still a hassle to have to do double escape to get an escape to macOS. Having kindaVim natively support CapsLock would be great.

All of this is mitigated by one of the best features of kindaVim--highlighting the window when kindaVim is active. I always wanted something like this in Karabiner--I was routinely confused by staying in normal mode when I switched apps and getting really confused. 

KindaVim is really good and useful work--thanks!

**Comment by godbout** [comment]
fuck i didn't think about `caps lock`. i have mine remapped to `esc` too. i got used to the double `esc` to exit, but i see your point. but in that case you would need to press `esc` with the real `esc` key, right? just wondering how this would work. i use my remapping in the whole macOS, not when i'm just in kV Normal Mode. if `caps lock` is `caps lock`, then you can't use it as `esc` anymore. shit it's getting late.

currently yeah you're only gonna be able to enter "valid" Keyboard Shortcuts, not *any* key. the hardcoded `esc` is a hack. i could add the option to use a couple of keys that are not valid Keyboard Shortcuts. then you could use one of those, or set your own Shortcuts like now. seems alright. will add it to the list. thanks!

**Comment by godbout** [comment]
> one of the best features of kindaVim--highlighting the window when kindaVim is active

and also LOL

**Comment by godbout** [comment]
how's the double escape? still an issue or used to it yet? :D
any other blockers?

**Comment by tthkbw** [comment]
I went back to Karabiner for mapping the CapsLock key. I wrote a quick Karabiner modification to map CapsLock to CMD-F9 and then mapped CMD-F9 to be the hotkey for KindaVim. This works well for me.

There is still some weird shit, though. For example, I use Drafts quite a bit, and kv works well there and I use it a lot. When I go into normal mode I get the block cursor. If I leave normal mode using 'i' or another command that enters insert mode, everything works perfectly (I get the non-block cursor which sits in between characters). But if I leave normal mode by hitting <ESC> or my hotkey, then the block cursor remains, meaning that the current character is highlighted. If I then start typing, I delete that character. I still haven't broken myself of this habit of leaving normal mode via <ESC> rather than the hotkey. 

Also, take a look at a new posting I made about a problem I think should be fixed.

**Comment by godbout** [comment]
> I went back to Karabiner for mapping the CapsLock key. I wrote a quick Karabiner modification to map CapsLock to CMD-F9 and then mapped CMD-F9 to be the hotkey for KindaVim. This works well for me.

so i'm still curious what's the workflow? do you ever use `esc`? if yes is it mapped to another key?


> There is still some weird shit, though. 

😀️

> For example, I use Drafts quite a bit, and kv works well there and I use it a lot. When I go into normal mode I get the block cursor. If I leave normal mode using 'i' or another command that enters insert mode, everything works perfectly (I get the non-block cursor which sits in between characters). But if I leave normal mode by hitting or my hotkey, then the block cursor remains, meaning that the current character is highlighted. If I then start typing, I delete that character. I still haven't broken myself of this habit of leaving normal mode via rather than the hotkey.

> Also, take a look at a new posting I made about a problem I think should be fixed.

yeah we talked about that one before. gonna answer in the new thread as this is related.

**Comment by tthkbw** [comment]
I do not have the <ESC> key mapped to anything. However, just because of muscle memory, I often hit <ESC> to exit normal mode in kv. I also use it often to cancel things like dialogs and the like. 

Generally my workflow for kv is simple:

1. I'm in a text box somewhere on my Mac. I need to edit stuff.
2. I hit CapsLock (mapped to CMD-F9, which is the hotkey for kv).
3. I am in normal mode and I happily go about my business. 
4. If I always remembered to exit normal mode by using 'i' or any other command that put me in insert mode, all would be well. But I still hit <ESC>, or perhaps CapsLock (the kv hotkey), and I am left with a highlight which gets deleted if I type something.

Still, I am getting better and kv is very useful to me.

**Comment by godbout** [comment]
don't get too better 😀️ i'll make some changes. see the other thread.

**Comment by godbout** [comment]
> 4. If I always remembered to exit normal mode by using 'i' or any other command that put me in insert mode, all would be well. But I still hit , or perhaps CapsLock (the kv hotkey)

still need some confirmation to make sure i get it right. you expect kV Normal Mode to leave to Insert Mode when pressing `esc`? even if it's not a Vim behavior. (`esc` stays in Normal Mode.)

> Still, I am getting better and kv is very useful to me.

good. we're at least two 😂️😂️😂️

**Comment by godbout** [comment]
i'm checking the caps-lock thing. i have two questions:
1. how is it working for you now? when you press your caps-lock mapped to cmd-F9, does your caps-lock actually turns ON? 
2. how would you expect kV to handle this? like overriding the default caps-lock behavior? like caps-lock actually never gets turned ON?

thanks.

**Comment by tthkbw** [comment]
I use Karabiner to map my caps lock key. The mapping is one of the clever ones that produces the CTRL key if you hold the key down, but sends CTRL-F9 if the key is tapped. There is a timeout associated with this which makes the decision as to whether there was just a press, or a press and hold. In my case, the Karabiner parameters are the defaults. Karabiner calls them "to_if_alone_timeout_milliseconds", which is set to 1000 ms, or 1 second, and "to_if_held_down_threshold_milliseconds" which is set to 500 ms or 1/2 second. These defaults seem to work really well for me. 

Having caps lock as control when held is really good for me since I began my serious computing work (and using vi work) on an old IBM PC-AT keyboard, which had the ctrl key in the position that is now taken up by capslock on almost all keyboards. That old PC-AT keyboard with its mechanical switches and huge throw and loud noises was the best keyboard I ever used on a computer.

**Comment by godbout** [comment]
so your caps-lock never works as a caps-lock right? i mean, i get it's remapped, but then if you press any letter you don't get the uppercase showing up? no little green light right?

**Comment by tthkbw** [comment]
That's correct, my caps-lock never works as a caps-lock. It only works as CTRL or CTRL-F9. 

And, my keyboard doesn't have a little green light, because my keyboard is an advanced piece of technology!

**Comment by godbout** [comment]
> That's correct, my caps-lock never works as a caps-lock. It only works as CTRL or CTRL-F9.

great, thank you! (hope you're enjoying the `/`, `?`, `N`, `n` etc btw.)

> And, my keyboard doesn't have a little green light, because my keyboard is an advanced piece of technology!

😄️

**Comment by godbout** [comment]
ok i was having a look at using `caps lock` as a key to enter Normal Mode and it happens that `caps lock` is a bit even more special that `escape` and basically you need to write your OWN FUCKING KEYBOARD DRIVER to catch it (which is what Karabiner is doing). so it seems the best way to get this working is what you did. using KE to remap. i'm not seeing this being implemented natively in kV.

can i close? 🥺

**Comment by tthkbw** [comment]
Go ahead and close it.

**Comment by godbout** [comment]
thank you Sir!
