### ISSUE TITLE
More motions and additions

### ISSUE THREAD

**Issue by tthkbw** [godbout/kindaVim.theapp#22]
I love that F, f, t, T are supported. I would be great to also support ';' to repeat these searches.

Having said that, the other thing that is muscle memory for me that would be useful to support is '/' for searching while in normal mode. I've only been using kindaVim for an hour, and I love it, but I have more than once messed shit (language in keeping with the kindaVim spirit!) up by trying to search with '/' and entering a search term that gets me out of normal mode.

Methinks that kindaVim is fucking (!!) transformative.

**Comment by godbout** [comment]
> but I have more than once messed shit 

FUCK YEAH THAT"S THE SPIRIT 🔥️🔥️🔥️ LMAO

yes, `;` and `,` (and probably also `.`) are in the plans. but tbh they may come after the subscription is out. they will require some heavy work as currently i don't keep track of previous moves. it's in the plans (that would also allow for better `u` and `r`) but i need to investigate. i *think* technically there's no reason that this wouldn't be possible tho. so just need to dig and find the way.

`/` also in the plans. this one may come earlier. i'm gonna start working on new heavier moves in a week or two and `/` will be part of it. fingers crossed.

thanks for the suggestions. they are FUCKING great additions.

**Comment by godbout** [comment]
already dismembered in their own issues.
