### ISSUE TITLE
`esc` in Raycast doesn't trigger Normal mode if "focused" app is blocked

### ISSUE THREAD

**Issue by neldeles** [godbout/kindaVim.theapp#23]
![CleanShot-2021-12-25-at-14 54 02@2x](https://user-images.githubusercontent.com/14298160/147379324-47aaf32e-505f-4b9f-9c33-ef8e2703d593.png)

So if any of  the blocked apps are focused, and I activate Raycast, `esc` doesn't trigger Normal mode for Raycast. If I activate Raycast from a non-blocked app e.g. Finder, `esc` does trigger Normal mode.

Here's how it looks like with Chrome:
![CleanShot-2021-12-25-at-14 59 59](https://user-images.githubusercontent.com/14298160/147379462-21934342-6dbe-4bf6-a69f-42cb5477bfa0.gif)

**Comment by godbout** [comment]
thanks for the big big pics. that helps a lot (i'm serious).

probably what happens here is that Raycast is some sort of popup and is not considered by macOS as the main active window. will dig into it. thanks for reporting and i hope kV hasn't destroyed your life.

**Comment by godbout** [comment]
so yeah currently kV checks what is the frontmost application but Raycast decided to be a non activating panel, so kV can't detect it. Alfred has an option to function like a proper app, which makes it work, but Raycast doesn't. so i guess, stuck for now. i'll see if i can be more of a genius somehow.

**Comment by tthkbw** [comment]
I use Alfred and have this problem. I can't find anywhere in Alfred preferences that makes this work. Can you give me a pointer to the setting?

**Comment by godbout** [comment]
for Alfred:

![Alfred_Preferences_and_`esc`_in_Raycast_doesn_t_trigger_Normal_mode_if__focused__app_is_blocked_·_Issue__23_·_godbout_kindaVim_theapp](https://user-images.githubusercontent.com/121373/147492710-e7af8f5c-8813-457f-a056-6cc4700f5824.jpg)

i personally use `compatibility` mode because the standard mode usually doesn't grab my first key.

**Comment by godbout** [comment]
> i'll see if i can be more of a genius somehow.

DJEENIUS CONFIRMED>

**Comment by neldeles** [comment]
> > i'll see if i can be more of a genius somehow.
> 
> DJEENIUS CONFIRMED>

LOL. Seeing this in my inbox gave me a chuckle and made my day. Excited for the fix 🎉

**Comment by godbout** [comment]
it's more than a fix. coming in 1b16 probably on the 31st midnight. love letter coming later.

**Comment by godbout** [comment]
@neldeles THANK YOU! i was using at first the official way of detecting the focused window and had no intention into digging deeper but thanks to your report i had to. found that the official fails in some cases. ultimately found some other nails and hammers. now kV is better than even, and you're responsible for that. so THANK YOU ❤️

**Comment by godbout** [comment]
in 1b16: https://github.com/godbout/kindaVim.theapp/releases/tag/1b.16
