### ISSUE TITLE
A few additional requests

### ISSUE THREAD

**Issue by tthkbw** [godbout/kindaVim.theapp#26]
1. Save any deletions to the clipboard for use with Put--anything deleted with 'x' 'X', 'd', 'c' and so on.
2. ‘x’ should work on visual mode selections the way ‘c’ and ‘d’ do.
3. Repeating ‘f’ and ’t’ commands with ’;’ would be a nice addition.
4. Even better, but a bit more complicated :) would be support for the dot (‘.’) command. This repeats the last command.
4. Searching with ‘/‘ and supporting ’n’ ’N’ would be great.
5. ‘~’ for changing case.
6. You need a solution for joining lines together while editing in Normal Mode, like vim’s ‘J’ command. Currently, I can’t do this in Normal mode. ‘X’ doesn’t work at the beginning of a line. Best I can figure out is to use the following sequence: ‘$vld’. This joins the lines, but deletes the last character of the first line. 
5. I love the dimming of background apps when using kindaVim to let me know that I am in Normal Mode. The drawback is that I often am editing in one app while looking at reference stuff from another. kindaVim dims the background so much that I can no longer read it.

**Comment by godbout** [comment]
does anyone know how to block spam on GH?

**Comment by tthkbw** [comment]
Well . . . All you have to do is ask. Sorry I have overwhelmed you.

**Comment by godbout** [comment]
i'm just kidding 😂️😂️😂️ sorry. hard to stay too serious in life. finishing something and i'll answer your requests. some responses you're gonna like, some a bit less 😄️

**Comment by godbout** [comment]
hello again! (i'm coming from the other thread.)

> * Save any deletions to the clipboard for use with Put--anything deleted with 'x' 'X', 'd', 'c' and so on.

all those coming in the next be'a (i'm actually using them myself at the moment 😎️). not all will be there at first because i need to review all the tests and moves which is gonna take time. gonna update the doc to show the progress for now.

> * ‘x’ should work on visual mode selections the way ‘c’ and ‘d’ do.

done already in be'a15. my research showed that Visual Mode `x` is actually Visual Mode `d`. i'm right am i?

> * Repeating ‘f’ and ’t’ commands with ’;’ would be a nice addition.

yes. but like said before, this requires saving previous commands. so it's a big change on the kV engine. so for later.

> * Even better, but a bit more complicated :) would be support for the dot (‘.’) command. This repeats the last command.

same.

> * Searching with ‘/‘ and supporting ’n’ ’N’ would be great.

regex work was supposed to start this week but there's stuff on top now. but i'm excited to dig into that soon.

> * ‘~’ for changing case.

😬️

> * You need a solution for joining lines together while editing in Normal Mode, like vim’s ‘J’ command. Currently, I can’t do this in Normal mode. ‘X’ doesn’t work at the beginning of a line. Best I can figure out is to use the following sequence: ‘$vld’. This joins the lines, but deletes the last character of the first line.

yeah i have that need too so probably i'll look at this soon but probably not before next year. 

> * I love the dimming of background apps when using kindaVim to let me know that I am in Normal Mode. The drawback is that I often am editing in one app while looking at reference stuff from another. kindaVim dims the background so much that I can no longer read it.

yeah got this too. you could disable it though for now and still be informed whether you're in Normal Mode through the block cursor and/or menu bar icon? 
later i could add a slider that lets you choose the opacity, but again to do it properly i'm gonna need some brain space and some time sitting down. currently it's a bit one move after the other. not a priority then but will be possible.

**Comment by tthkbw** [comment]
With respect to showing Normal Mode in other ways:

Cursor change could be effective. Maybe some fancy colors would make it stand out more. Problem with this is that if you are in Normal Mode and you try to do something like CMD-Tab to switch apps, your eyes are probably not focused on the cursor and and it will take a bit longer to realize what has gone wrong. This type of thing is why I really like the dimming of background apps. 

I would probably have a lot of difficulty noting anything about changes to the menu bar icon. 

For me, the best solution would be allowing the dimming to be configured. I realize that is some work and will only happen later. 

And, yes, I believe that 'x' and 'd' are identical when they are executed and there is a visual highlight.

**Comment by godbout** [comment]
opacity option will come before any custom block cursor. currently it's using the cursor of the app you're on. i saw some people playing with custom cursor and it's a project on itself (5US a month that one). not sure when it's coming tho. hopefully i'm still alive next year 🤞️

**Comment by godbout** [comment]
> * ‘~’ for changing case.

what's your use of `~`? Normal Mode? Visual Mode? count? the variants? `g~` `guu` `omicron`?

**Comment by tthkbw** [comment]
I use ~ a lot, usually just by itself. Since it moves the cursor to the right, if I want to all-caps something, I usually just repeat the single key. However, I occasionally make use of visual mode selections to change case (this is usually because I have copied something long that is all caps). I rarely used count in Vim (takes to long to figure out what the count should be), but sometimes they are quite useful, particularly in macros. Similarly, I don't often use 'g' movements in Vim.

With particular respect to usage in kindaVim, I use ~ to fix cases where I missed timing on the shift key and ended up with a word that was supposed to be capitalized but was not. It is a big timesaver, keystroke saver, since I don't need to change back and forth between Normal and insert modes.

**Comment by godbout** [comment]
1. done
2. done 
7 and 8 done in 1b16: https://github.com/godbout/kindaVim.theapp/releases/tag/1b.16

**Comment by godbout** [comment]
gonna open separate issues for the other ones and close this one.

**Comment by godbout** [comment]
~ 👀️ #30

**Comment by godbout** [comment]
@tthkbw `N` and `n` coming in kV5.

**Comment by godbout** [comment]
> 4\. Even better, but a bit more complicated :) would be support for the dot (‘.’) command. This repeats the last command.

i've been starting work on the `.` motion. but i need a bit of feedback. how do you use it yourself in Vim? to repeat which motions? do you repeat the text you just typed sometimes with the `.`? do you still use kV? 😅️
