### ISSUE TITLE
The application “kindaVim.app” can’t be opened.

### ISSUE THREAD

**Issue by albert-ying** [godbout/kindaVim.theapp#33]
Hi, thank you for this tool! I tried to open it, it gives me an error

<img width="254" alt="image" src="https://user-images.githubusercontent.com/59846322/147886520-817e0832-e7d5-4741-8503-d95835118111.png">

and when I do

```
❯ open "/Applications/kindaVim.app"
```

It gives
```
The application cannot be opened for an unexpected reason, error=Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x60000251b7e0 {Error Domain=NSPOSIXErrorDomain Code=111 "Unknown error: 111" UserInfo={NSLocalizedDescription=Launchd job spawn failed}}}
```

**Comment by godbout** [comment]
😯️

1. downloaded from kindavim.app or GitHub?
2. if GitHub, latest version? (1b17)
3. which macOS? the Monterey be'a only works on... Monterey 😅️

**Comment by albert-ying** [comment]
I'm on M1 Monterey. Downloaded from the website link. Should I try the GitHub version instead?

**Comment by godbout** [comment]
hmm. that's gonna be a tough one. the error reported by macOS doesn't help. kV is built for Monterey, Intel and Apple silicon so your setup should work. tried on a brand new setup here and it works fine.

can you try 1b16 or 1b15?
* https://github.com/godbout/kindaVim.theapp/releases/tag/1b.16
* https://github.com/godbout/kindaVim.theapp/releases/tag/1b.15

hopefully it's just a bad download 😬️

**Comment by godbout** [comment]
1b18 out. maybe try that one? smooth update on my side on all the computers.

**Comment by albert-ying** [comment]
Thank you for the reply. Still not working tho. 

I use Yabai (a window tilling manager) and disabled the system integrity protection. Could it be related to this? https://github.com/koekeishiya/yabai/wiki/Disabling-System-Integrity-Protection

**Comment by godbout** [comment]
had no idea people would do that. kV doesn't do anything special apart from what's allowed by the Accessibility so that shouldn't be the issue, but will try. thanks.

**Comment by godbout** [comment]
disabled SIP. reset Defaults. brand new installation. works.

but seems some people are reporting something similar with apps on M1. 

can you try this: `chmod +x /Applications/kindaVim.app/Contents/MacOS/kindaVim` just to make sure it's not a permission issue.

**Comment by godbout** [comment]
P.S.: i have kV users running it on M1 so your issue may be more specific.

**Comment by godbout** [comment]
are you admin of your account? any parental control? 😅️

**Comment by godbout** [comment]
that's plain weird but ok. enjoy ☀️
feel free to report any issue you're finding, motions missing, feature you'd like etc. thank you!
