### ISSUE TITLE
FN shortcut for emojis not working anymore

### ISSUE THREAD

**Issue by Fabbi** [godbout/kindaVim.theapp#35]
What the title says. 
The FN/globe key to open emoji selection does not work with kindaVim running 😔

**Comment by godbout** [comment]
☹️

**Comment by godbout** [comment]
i can confirm. what a dumb app. will check, thanks.

**Comment by godbout** [comment]
fixed for 1b20. should come out in a few days 🚀️

**Comment by godbout** [comment]
1b20 released: https://github.com/godbout/kindaVim.theapp/releases/tag/1b.20
