### ISSUE TITLE
Will KindaVim support install by Homebrew ？

### ISSUE THREAD

**Issue by suliveevil** [godbout/kindaVim.theapp#37]
Will KindaVim support install by Homebrew ？

**Comment by godbout** [comment]
i don't see any reason why we wouldn't be able to do that, yeah. i'll check to make a cask.
just curious, any other use than for automated install through a `Brew` file?

**Comment by disrupted** [comment]
another advantage to me is that I can disable update checks for kV, Homebrew takes care of updating it.

**Comment by godbout** [comment]
> another advantage to me is that I can disable update checks for kV, Homebrew takes care of updating it.

ah. i love those answers. makes me see a lot of things that i didn't bother with till now. that means there's probably a need for an option to deactivate the update checks from kV itself (currently automatic every 24h), and also a better change log because i was relying on the internal updates to inform the users of the changes.

will digest. thanks!

**Comment by godbout** [comment]
although JFI delta updates coming soon. i don't think those are handled by `Homebrew`. currently download is quite small (around 3meg) but might be a little bigger in the future.

**Comment by godbout** [comment]
actually if you guys have any experience with Casks on Homebrew you could do the PR yourself 😅️ else i'll do it but need to do some research first to do it properly.

**Comment by godbout** [comment]
PR done: https://github.com/Homebrew/homebrew-cask/pull/117985. now 🤞️🤞️🤞️

**Comment by godbout** [comment]
merged.

currently it's the beta there, but probably later i'll add the version with subscription. if it's the case i'll make the latest beta available on homebrew-cask-versions (https://github.com/Homebrew/homebrew-cask-versions) so you'll always be able to download it there if you're happy with the current state.

**Comment by godbout** [comment]
kV1 is out. it's being put in homebrew-cask, while 1b25 is being put in homebrew-cask-versions. just pay attention when you upgrade :p

**Comment by godbout** [comment]
ok so regarding homebrew the old 1b25 beta can't be put in homebrew-cask-versions (see https://github.com/Homebrew/homebrew-cask-versions/pull/13248). so you'll have to download it on GitHub. anyways, it'll never get updated.

for the stable version i'll keep updating it in homebrew-cask.
