### ISSUE TITLE
Disabling obsidian does not work

### ISSUE THREAD

**Issue by sahewat** [godbout/kindaVim.theapp#39]
I've disabled obsidian by dragging it into the relevant (leftmost) box from the Applications folder but kindaVim requires me to type escape twice to exit insert mode.

**Comment by godbout** [comment]
indeed. can reproduce in 1b23. this is because you can't even get the PID of Electron apps properly with the macOS Accessibility. i've added a billion workarounds in 1b24 which should bring full Electron apps support. will be out today or over the weekend. thanks for reporting.

**Comment by godbout** [comment]
1b24 out. should be ok now 🚀️
