### ISSUE TITLE
`x` doesn't work on safari

### ISSUE THREAD

**Issue by kcmannem** [godbout/kindaVim.theapp#42]
on safari text/input fields, the `x` move does not delete the currently highlighted character

**Comment by godbout** [comment]
bonjour. yes at the very first this was a supposed to be psychological trick. like people would get annoyed it doesn't work, they post here, i solve their issue easily and they fall in love with me. but that experiment proved to be a big failure ☹️

but thanks for the reminder. i've tried several ways before, like hardcoding apps, or defaulting like you're saying. always felt not cool to scan the users' systems tho. never found a good *balance* but maybe defaulting to **built-in** apps is the one. gonna digest this.

i'm a bit wary though that it prevents users from exploring the `Families` preferences. to be able to handle most of macOS apps users will definitely have to play around with the `Families` and should get familiar with it. any thoughts on this? how long did it take you to find out yourself?

there's a video about this here: https://www.youtube.com/watch?v=3dTNQ-XMDPI
there was something in the README also but too much text and too technical, most people would skip i think.

**Comment by godbout** [comment]
created a discussion for this here: https://github.com/godbout/kindaVim.theapp/discussions/48

thanks for reporting! closing this one.
