### ISSUE TITLE
Arrow keys?

### ISSUE THREAD

**Issue by bromanko** [godbout/kindaVim.theapp#46]
Is it possible to use arrow keys for movement rather than hjkl? I use the Colemak-DM layout which moves those keys off of the home row. I use a layer with arrow keys on my home row that is in the same location. This works fine in Vim but doesn't work in kindaVim.

**Comment by godbout** [comment]
currently only `<Left>` is implemented. i'll add the other ones to the next update. seeing the past record it should be out in a couple of days 😅️

Colemak (and any keyboard layout actually) should be handled properly (https://github.com/godbout/kindaVim.theapp/issues/12). but just to make sure can you confirm that `<Left>` is working with your setup? thanks a ton!

**Comment by godbout** [comment]
btw if you've got some other moves missing just let me know. the plan is to have all of them implemented but priorities on the ones i use myself ( 🙈️ ) and the ones requested by users. the moves requested go at the top of the pile.

**Comment by bromanko** [comment]
Thanks for the quick response. Left does work! I thought that was odd but now it makes sense. 

FWIW my Colemak layout is in the keyboard firmware. I don’t change the OS keyboard layout. So other motions have been fine.

**Comment by godbout** [comment]
kV8 out: https://github.com/godbout/kindaVim.theapp/releases/tag/8

`<Up>`, `<Right>`, `<Down>` added. plus some more. plus all with counts 💫️

**Comment by godbout** [comment]
thanks for mentioning they were missing. kV is not better thanks to you!

**Comment by godbout** [comment]
oh btw `<NL>` is supposed to go down too, but i'm not sure if this even available on Mac keyboards? i thought at first that it was the `keypad enter` but no, this one is `<Enter>`. `return` is `<CR>`. so `<NL>` is indeed `newline`, but no idea if this is doable on your keyboard :D

**Comment by bromanko** [comment]
Thanks for the quick addition! It works great.

**Comment by godbout** [comment]
@bromanko i'm curious. don't you have any issue with moves that include the arrow keys? like `dj` for example. i've implemented the arrow keys but not the moves that include them. i'll do that for the next update. but was wondering how come this doesn't seem to be an issue for you. thanks!

**Comment by bromanko** [comment]
Looks like that doesn't work for me either. That's not a common case for me to do so I didn't catch it.

**Comment by godbout** [comment]
ok, that makes sense then. coz if it was working that's probably mean it'd be time for me to retire... 😂
i'll add all the moves that include the arrow keys and i'll close back the issue. thank you!

**Comment by godbout** [comment]
ok, done in kV14: https://github.com/godbout/kindaVim.theapp/releases/tag/14
