### ISSUE TITLE
bought subscription but cannot add apps to off list such as my terminal theres simply no button to add apps 

### ISSUE THREAD

**Issue by NikosEfthias** [godbout/kindaVim.theapp#51]
<img width="636" alt="image" src="https://user-images.githubusercontent.com/9097437/156326158-d857c3d9-2835-4471-8305-b3b2f133f6f5.png">
no way to add apps

**Comment by NikosEfthias** [comment]
yesp figured out thats why closed the issue thanks :) @godbout btw still cant get brave browser text input to work even after adding it to PG-R list

**Comment by godbout** [comment]
thanks for posting this as a new issue! forwarding the answer there.
