### ISSUE TITLE
add `CTRL-D` and related moves to the Accessibility Strategy

### ISSUE THREAD

**Issue by godbout** [godbout/kindaVim.theapp#60]
coming from https://github.com/godbout/kindaVim.theapp/issues/58.

**Comment by godbout** [comment]
this requires work with `Screen Lines`. past work in this area hasn't been successful. there were a lot of things not working with the [kAXVisibleCharacterRangeAttribute](https://developer.apple.com/documentation/applicationservices/kaxvisiblecharacterrangeattribute#), whether when getting or setting AX info.

**Comment by godbout** [comment]
past work: https://github.com/godbout/AXEngine/blob/b2c1cac18658e098322d061c66f991335e13c215/Sources/AXEngine/AXEngine.swift#L317

**Comment by jjjchens235** [comment]
subbed

**Comment by godbout** [comment]
`CTRL-D` 
`CTRL-U` 
`CTRL-B` 
`CTRL-F` 
added in kV13: https://github.com/godbout/kindaVim.theapp/releases/tag/13

but only the positioning of the caret is correct. the scrolling is not. big piece. doesn't seem to be able to be done properly/with consistency.

**Comment by godbout** [comment]
gonna close that one now that the moves are down. i'll see later if there's a need to handle the scrolling better. if yes then i'll open a new issue for that.
