### ISSUE TITLE
add `zz`, `zb`, `zt` and alike

### ISSUE THREAD

**Issue by godbout** [godbout/kindaVim.theapp#62]
talked about there: https://github.com/godbout/kindaVim.theapp/issues/58

**Comment by godbout** [comment]
looking good!

**Comment by godbout** [comment]
done in 15: https://github.com/godbout/kindaVim.theapp/releases/tag/15

but two things:
1. done only for Normal Mode. Visual Mode requires a complete other set of tests and implementations
2. no count for now. count is harder than expected for those moves. will do if requested explicitly

**Comment by jjjchens235** [comment]
This is working amazing in TextEdit. Fantastic work man, and as usual, thank you!

**Comment by godbout** [comment]
nice. THANK YOU! need the little push to get those done :D

**Comment by godbout** [comment]
@jjjchens235 at least someone will be able to play with their new moves in Thailand.

![aVlopq4B_700w_0](https://user-images.githubusercontent.com/121373/162555886-cb426ce3-ba92-4f1c-a929-f48fdbfa102d.jpg)

😂️😂️😂️
