### ISSUE TITLE
Popup to pay / register a license cuts off screen

### ISSUE THREAD

**Issue by dbalatero** [godbout/kindaVim.theapp#65]
<img width="226" alt="image" src="https://user-images.githubusercontent.com/59429/163377278-1e1a8618-610b-4397-9ae4-b649420aa334.png">

Repro

1. Open kindaVim, without a license
2. Open Chrome window, position it in top left of screen
3. Click in the address bar, near `http://`
4. Enter Vim
5. Hit something like `dw`
6. The popup will cut off and go off screen

**Comment by godbout** [comment]
any chance that you're using Bartender or any other app that is hiding status bar items, and kV is hidden? coz it's the case that's "normal". that happens with mostly most apps as they popover is supposed to be shown below the app icon. Bartender (or similar apps) hide the status bar items by sending them into outer space.

if this is the case then i'm aware and not planning to fix that one. if not, then i'll dig into more. let me know! thanks.

**Comment by godbout** [comment]
@dbalatero btw, about this one so, were you using something like Bartender?

**Comment by godbout** [comment]
gonna close that one. please reopen if you wanna add something.
