### ISSUE TITLE
Disable For App Menu

### ISSUE THREAD

**Issue by rkabrick** [godbout/kindaVim.theapp#67]
First and foremost... This is dope. Oh, so dope.

Works unbelievably well. I am wondering if there is a way (without compiling from source) to disable it for my Terminal application? I use Warp as a terminal application and while using kindaVim I have to  hit Esc twice in order to utilize my leader key in Vim. It'd be neat to offer the user control over what apps to use it for and what not.

**Comment by godbout** [comment]
if i get you correctly, what you're looking for is putting `Warp` in the `Off Family`:

![Screen Shot 2022-04-27 at 13 41 04](https://user-images.githubusercontent.com/121373/165449041-de8857e6-69d8-493c-8472-8e7529dcf4ff.png)

as soon as `Warp` will be the frontmost application, kV will back off. i think this is what you're looking for but let me know if i got you wrong.

**Comment by godbout** [comment]
oh and yes you need to drop the app. no `+``-` buttons coz you wouldn’t believe how actually lazy i am. to remove an app, right click delete.

**Comment by rkabrick** [comment]
you wouldn't believe how stupid I am :) 

Tbh if you told me I was this stupid yesterday I probably wouldn't have believed you. I simply did NOT realize there was a menu bar preferences menu. In my defense I use Bartender but still, for me not to check is telling. 

Well... while I'm off getting formally diagnosed as an a**hat please continue to make beautiful software :)
