### ISSUE TITLE
[suggestion] Add custom keyboard command to send escape to macOS

### ISSUE THREAD

**Issue by bromanko** [godbout/kindaVim.theapp#68]
Right now you can press Esc twice to send escape to macOS. It would be nice to customize this. I'd prefer something like M-Esc or C-Esc.

**Comment by godbout** [comment]
so if i get you correctly, that means basically overriding macOS default `escape` to another keyboard shortcut? you'd use M-Esc or C-Esc while in Insert Mode to do what a normal `escape` does if you didn't have kV installed, right?

if yes that's definitely possible. although afaik there's no proper paid or open source Swift keyboard shortcut library that handles recording funky stuff like `escape`, `caps lock`, or double keys. i have/had in the pipeline to build one but it's massive work. we could start with a dropdown that lets you add `control`, `option`, `shift` or `command` to `escape` if you use `escape` to enter Normal Mode.

**Comment by bromanko** [comment]
Thanks for the additional information. I can now see why this is more complicated. Perhaps I'm better off using something other than escape to enter Normal mode. Let me give that a shot first.

**Comment by godbout** [comment]
well i'm still gonna add some options. i've had some other people labelling the double escape as gross :D personally i like it (capslock is my escape, very quick to double it) but i can see the need for another way. so if you'll choose entering Normal Mode with `escape` in kV, you'll have a dropdown to choose how to send `escape` to macOS instead. the dropdown will have at least `double escape`, `control escape` and `option escape`. may add `command escape` and `shift escape` but need to dig a bit more into it first.

i wanna do a few more things first: 1) add passthrough with option key 2) improve the whole Preferences UI 3) add a couple of more tests for the Characters Window. but after those i can work on it. probably in about two weeks.

**Comment by godbout** [comment]
> so i'm currently adding this into kV20 and FWIW `⌘⎋` works out of the box already in macOS 😅️

ok my bad. it was coz kV was running in the background with the new feature and `⌘⎋` was set as the option to send `⎋` to macOS... time for a break.

**Comment by bromanko** [comment]
Haha. Oh my. Time for a break indeed. Looking forward to the update!

**Comment by bromanko** [comment]
Yes! This is amazing. Thank you so much!

**Comment by godbout** [comment]
it's me! thanks for the request. making kV better.
