### ISSUE TITLE
add OmniOutliner

### ISSUE THREAD

**Issue by yuvalgavish** [godbout/kindaVim.theapp#73]

**Comment by godbout** [comment]
thanks for being the first! will be in kV22 👍️

**Comment by godbout** [comment]
@yuvalgavish the label should have been applied automatically though. do you mind letting me know through which browser did you enter the issue? may be an emoji encoding issue, but Safari/Google Chrome/Brave Browser/Firefox should all work.

**Comment by godbout** [comment]
added in 22 https://github.com/godbout/kindaVim.theapp/releases/tag/22
