### ISSUE TITLE
If I wanted to commit my Preferences to my dotfiles, what should I do?

### ISSUE THREAD

**Issue by dbalatero** [godbout/kindaVim.theapp#85]
I'd like to move the kindaVim preferences to my [dotfiles](https://github.com/dbalatero/dotfiles), and then symlink them back to whether the app expects them to live.

What folder should I move to Git if I wanted to do that? Something in `~/Library/Preferences` maybe?

**Comment by godbout** [comment]
it feels like you keep reading my mind!

i've added a PR to mackup at the beginning of the year, which is tool that backs up and restores config files through symlink, i guess like the dotfiles: https://github.com/lra/mackup/pull/1811/files. they still haven't merged though, not sure why.

anyways, the Preferences files is there: `~/Library/Preferences/mo.com.sleeplessmind.kindaVim.plist`

i thought about adding a sync option in the Preferences, through Dropbox or something. but not sure if this is useful? like you may actually have different apps on different computers, or even use the Characters Window on one but not on the other, depending how you use the different computers. so i haven't done it (yet). thought i'd do the PR on mackup yet. lemme know if you think that'd be good to add something in the Preferences, a la Alfred style (although for kV currently yes, it's just one file. but might more later).

**Comment by dbalatero** [comment]
Great, I will use that `plist`.

> i thought about adding a sync option in the Preferences, through Dropbox or something. but not sure if this is useful?

Not to me, as I have to run work Dropbox on my work computer and personal on my others, so I couldn't use that if I wanted to.

Sidenote, one of the reasons I run Alacritty is that the terminal config is a portable YAML file that is plain text and can be easily checked in and diffed. Prior to that, I used iTerm and sync'd plist files, and the git diffs were pretty hard to read.

I'm not saying you should not use plists (it seems to be the config-du-jour of macOS apps) but just food for thought maybe.

**Comment by godbout** [comment]
> Sidenote, one of the reasons I run Alacritty is that the terminal config is a portable YAML file that is plain text and can be easily checked in and diffed. Prior to that, I used iTerm and sync'd plist files, and the git diffs were pretty hard to read.
> 
> I'm not saying you should not use plists (it seems to be the config-du-jour of macOS apps) but just food for thought maybe.

i would believe that almost all native apps use plists (Alacritty is written in Rust). it's not really that we "decide" to use plists. it happens behind the scenes. it's just that for small settings, Apple provides us with easy, out of the box, abstract APIs. how they store the settings behind is up to Apple. they could replace those by xml files that it wouldn't change anything to our apps themselves. in AppKit it used to be `UserDefaults`. in SwiftUI it's even easier. you declare a variable with the `@AppStorage` wrapper and that's it, your variable is stored as a preference. with all the goodies out of the box like caching (the settings are not written to disk live), saving if the app or the OS crashes, etc. of course using those APIs and plists is not mandatory, but then you need to write your own system, or use a (tested) third party library.

for kV i had some stuff in mind. but usual, it's just floating thoughts. i can have a concrete idea only when i decide to focus on that part and spend some weeks researching, experimenting, etc. i thought first of the mackup tool, then having some sort of `copy Preferences to clipboard`—that could be yaml—that would paste on your other computer. then Dropbox/iCloud Drive/etc. maybe if later there's something bigger, like an App Catalog database. but as long as it's not a priority, those are just floating thoughts :p

**Comment by godbout** [comment]
solved. let's see if we need another solution later, depending on users' requests.
