### ISSUE TITLE
Add wizard support for other Discord clients

### ISSUE THREAD

**Issue by Kyle-Mendes** [godbout/kindaVim.theapp#87]
The wizard knows about Discord, but not the Canary and PTB builds! It would be helpful to add those as well.

## Discord App
<img width="601" alt="image" src="https://user-images.githubusercontent.com/6400039/173430482-41eed662-b784-425c-a99f-ea3cd482cfeb.png">

## Discord Canary
<img width="596" alt="image" src="https://user-images.githubusercontent.com/6400039/173430538-07550fae-bf56-4e05-9934-d9c84484cf44.png">

## Discord PTB
<img width="589" alt="image" src="https://user-images.githubusercontent.com/6400039/173430778-d1c174b7-b159-4490-8604-660cee752ffa.png">

**Comment by godbout** [comment]
will do for next release, thanks. although the text will be the same (Discord doesn't play well at all with macOS standards. they've acknowledged the issues. hopefully they'll do something about it).

**Comment by godbout** [comment]
added in kV25: https://github.com/godbout/kindaVim.theapp/releases/tag/25
